development:
  adapter: postgresql
  encoding: unicode
  database: app_development
  pool: 5
  username: rbates
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: app_test
  pool: 5
  username: rbates
  password: