# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b041a349222bcfb7c524841a86f20b6a39a6efbb90c7605615a652637ad13511e2baed1fdeb3437e21346317296e76fb3757aca8832d36a8dfc9d4a59e0ccfc

test:
  secret_key_base: 63c46b0fb84669b4ab1e6b33a8dcde2d294cc65bc4ad3f33a8805bded9d5f77994b2f7bdae79c9b339bcae0fc45c7a6492da1d47725f159f59d7947c5c4a4388

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
